version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch-scm
    steps:
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - checkout
      - run:
          name: Do a build
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            COMMIT_RANGE=8b2900a83bbb...21a1e4c5ec38
            ./do-a-build.sh ${COMMIT_RANGE}
