version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install packages
          command: apt-get update && apt-get install -y git docker
      - checkout
      - run:
          name: Do a build
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            COMMIT_RANGE=8b2900a83bbb...21a1e4c5ec38
            ./do-a-build.sh ${COMMIT_RANGE}
